version: '3'

services:
  test-server:
    restart: always
    build:
      context: ./
    
    volumes:
      - ./dependencies/:/root/.m2
    ports:
      - "80:8080"
      - "443:8443"
    depends_on:
      - test-mysql

  test-mysql:
    image: mysql:5.7.19
    volumes:
      - ./database:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ekar_test
   
    ports:
      - 3306:3306
